name: Send repository_dispatch event to parent repo  
  
on:  
  push:  
    branches:  
      - master
  
jobs:  
  notify-parent-repo:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Repository Dispatch  
        uses: peter-evans/repository-dispatch@v2  
        with:  
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: LgHS/lghs.be
          event-type: sync-shared-submodules
